Gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls')),
    path('accounts/', include('allauth.urls')),
    path('store/', include('store.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls import url
from django.views.generic import View, ListView
from .models import Item, ItemImage

app_name = 'main'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),

    re_path('details/(?P<pk>\w+)/', views.Details.as_view(), name='details'),

    path('zoo/', views.ListView.as_view(queryset=ItemImage.objects.filter(category__category='zoo').order_by("-updated"), template_name='works/zoo_all.html'), name='zoo_all'),
    path('portraits/', views.ListView.as_view(queryset=ItemImage.objects.filter(category__category='portrait').order_by("-updated"), template_name='works/portraits_all.html'), name='portraits_all'),
    path('portraits_bw/', views.ListView.as_view(queryset=ItemImage.objects.filter(category__category='bw_portraits').order_by("-updated"), template_name='works/portraits_bw_all.html'), name='portraits_bw_all'),
    path('landscapes/', views.ListView.as_view(queryset=ItemImage.objects.filter(category__category='landscape').order_by("-updated"), template_name='works/landscapes_all.html'), name='landscapes_all'),
    path('flowers/', views.ListView.as_view(queryset=ItemImage.objects.filter(category__category='flower').order_by("-updated"), template_name='works/flowers_all.html'), name='flowers_all'),


    path('about/', views.AboutView.as_view(), name='about'),
    path('lessons/', views.LessonsView.as_view(), name='lessons'),


    path('add/', views.ItemAdd.as_view(), name='item_add'),
    re_path('comment/(?P<pk>\w+)/delete/$', views.CommentDelete.as_view(), name='comment_delete')


]

store/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls import url
from django.views.generic import View, ListView
from item.models import Item, ItemImage

app_name = 'store'

urlpatterns = [
    path('', views.StoreView.as_view(), name='store_index'),
]

item/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    category = models.CharField(max_length=120, default=None)

    class Meta:
        db_table = 'Category'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category


class Item(models.Model):

    name = models.CharField('Name', max_length=256)
    description = models.TextField(max_length=500)
    is_active = models.BooleanField(default=True)
    price = models.FloatField('Price')
    category = models.ForeignKey(Category, default=0, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        ordering = ['created']
        verbose_name = 'Item'
        verbose_name_plural = 'Items'

    def get_absolute_url(self):
        return reverse('main:works')


class ItemImage(models.Model):

    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    image = models.ImageField('Image', upload_to='')
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(Category, default=0, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return '%s' % self.item

    class Meta:
        verbose_name = 'Item\'s image'
        verbose_name_plural = 'Images'


class Comment(models.Model):
    post = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    text = models.TextField(max_length=500)

    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)


    class Meta:
        ordering = ['created']
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

store/models.py
from django.db import models
# Create your models here.

item/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

item/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import CommentForm
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect


class Index(View):

    def get(self, request):
        zooimg = ItemImage.objects.filter(category__category='zoo')
        portrait = ItemImage.objects.filter(category__category='portrait')
        bw_portraits = ItemImage.objects.filter(category__category='bw_portraits')
        landscape = ItemImage.objects.filter(category__category='landscape')
        flowers = ItemImage.objects.filter(category__category='flower')
        front = [flowers.reverse()[0], portrait.reverse()[0]]

        return render(request, 'main/index.html', locals())



class LessonsView(View):

    def get(self, request):
        return render(request, 'main/lessons.html', locals())


class AboutView(View):

    def get(self, request):
        return render(request, 'main/about.html', locals())




# class Zoo(View):
#
#     def get(self, request):
#         worksImg = ItemImage.objects.all()
#         return render(request, 'main/works.html', locals())


class ItemAdd(CreateView):
    template_name = 'forms/item_add_form.html'
    model = Item
    fields = '__all__'


class Details(DetailView):

    def get(self, request, pk):
        post = get_object_or_404(Item, pk=pk)
        comment = Comment.objects.filter(post=post)
        comment_form = CommentForm()
        return render(request, 'main/picture_page.html', locals())

    def post(self, request, pk):
        post = Item.objects.get(pk=pk)
        comment = Comment.objects.filter(post=post)
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid:
            comment_post = comment_form.save(commit=False)
            comment_post.user = request.user
            comment_post.post = post
            comment_post.save()

            return render(request, 'main/picture_page.html', locals())


class CommentDelete(DeleteView):
    model = Comment
    success_url = reverse_lazy('main:works')

store/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView
from item.models import *
# Create your views here.


class StoreView(View):

    def get(self, request):
        zoo = ItemImage.objects.filter(category__category='zoo')
        portrait = ItemImage.objects.filter(category__category='portrait')
        bw_portraits = ItemImage.objects.filter(category__category='bw_portraits')
        landscape = ItemImage.objects.filter(category__category='landscape')
        flowers = ItemImage.objects.filter(category__category='flower')
        all = ItemImage.objects.filter(is_active=True)
        return render(request, 'store/store_index.html', locals())

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'AnimateCSS/animate.css' %}">
</head>
<body>

    <div id="wrapper">
    {% include 'header.html' %}
    {% block content %}
    {% endblock %}
    </div>
    {% include 'footer.html' %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'jQuery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/script.js'%}"></script>
    <script src="{% static 'jQuery/page-scroll-to-id-master/js/jquery.malihu.PageScroll2id.min.js'%}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js'%}"></script>
    <script defer src="{% static 'Font awe/fontawesome-free-5.0.2/svg-with-js/js/fontawesome-all.min.js' %}"></script>
</body>
</html>

templates/comming.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/soon.css' %}">
</head>
<body>

</body>
</html>

templates/footer.html
<div class="container footer">
    <div class="row">
        <div class="socials nav-pills">
            <li>Follow my socials:</li>
            <li ><a href="https://www.facebook.com/KiraArt.nz"><i class="fab fa-facebook-square fa-2x float-right"></i></a></li>
            <li><a href="https://www.instagram.com/kira_art_nz/"><i class="fab fa-instagram fa-2x float-right"></i></a></li>
        </div>
    </div>
</div>

templates/forms/item_add_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
        {% for field in  form%}
            {{ field.error }}
            <label>{{ field.label_tag }}</label>
            {{ field }}
        {% endfor %}
        <button class="btn btn-default" type="submit">Add</button>
    </form>>
{% endblock %}

templates/header.html
{% load account %}
<div class="container-fluid">
    <div class="row">
        <nav id="top" role="navigation" class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div id="navbar-collapse" class="collapse navbar-collapse  header">
                    <div class="row">
                        <div class="col-lg-12 col-lg-offset-1">
                            <ul class="nav nav-pills">
                                <li class="active"><a href="/">Home</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gallery <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url 'main:zoo_all' %}">Zoo</a></li>
                                        <li><a href="{% url 'main:portraits_all' %}">Portraits</a></li>
                                        <li><a href="{% url 'main:portraits_bw_all' %}">Portraits B/W</a></li>
                                        <li><a href="{% url 'main:landscapes_all' %}">Landscapes</a></li>
                                        <li><a href="{% url 'main:flowers_all' %}">Flowers</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'main:lessons' %}">Lessons</a></li>
                                <li><a href="{% url 'store:store_index' %}">Store</a></li>
                                <li><a href="{% url 'main:about' %}">About</a></li>
                                <li><a href="#">Contacts</a></li>
                                {% if  user.username%}
                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% user_display user %}<span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'account_logout' %}">Log Out</a></li>
                                        </ul>
                                    </li>
                                 </ul>
                                {% else %}
                                    <li><a href="{% url 'account_login' %}">Log In</a></li>
                                    <li><a href="{% url 'account_signup' %}">Register</a></li>
                                {% endif %}

                                {% if user.is_staff %}
                                <li><a href="{% url 'main:item_add' %}">Add picture</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</div>

templates/main/About.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container lessons">
        <div class="row">
            <img src="{% static "img/kira.jpg" %}" class="img-responsive">
            <p>
Hi, I'm Tanya


Here is a bit about me.
I was born surrounded by boxes of photographs and I fall in love with this magic from my early childhood... as a viewer :) I grew up inspired by examples of old european school of portrait photography and by learning from the photographic works of my grandfather -

a lifelong photographer, but never dreamt to be photographer myself when was a kid.


Happened, that photo retouching came first to my life as something really serious and very passionate. Through it I found my way to becoming a photographer.

​

I was a child who rarely smiled on the photos, I hated when people took photos of me, so I know how you feel when I'm pointing my camera on you.

Now I do self-portraits time after time, to keep myself being aware of your feelings and am constantly learning to make your photographic experience  better.

Love people, love diversity and believe everyone is beautiful it's just a matter of finding photographer that can see beauty in you and is able to show it to the world. I might be yours or might be not, but keep searching there is the one somewhere on the Earth ;)

​

​

​

I hope you've found something interesting for yourself on Tanya's ARTelier website.

Thank you for stopping by.



Tanya Mishchuk,

Internationally published Photographer, Photo Retoucher, Artist,

Founder of Tanya's ARTelier.</p>
        </div>
    </div>
{% endblock %}

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="zoo" class="container">
        <div class="row">
            <div pause = 'hover' keyboard = true data-interval="10000" id="zoo-carousel" class="index-padding-10per carousel slide" data-ride="carousel">
              <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    {% for image in zooimg %}
                        {% if forloop.first %}
                        <div class="item active">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% else %}
                        <div class="item">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>

              <!-- Controls -->
                <a class="left carousel-control" href="#zoo-carousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#zoo-carousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                </a>
            </div>
        </div>
    </div>
    <div id="portraits" class="container">
        <div class="row">
            <div keyboard = true data-interval="10000" id="portraits-carousel" class="index-padding-10per carousel slide" data-ride="carousel">

              <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    {% for image in portrait %}
                       {% if forloop.first %}
                        <div class="item active">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% else %}
                        <div class="item">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>

              <!-- Controls -->
                <a class="left carousel-control" href="#portraits-carousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#portraits-carousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                </a>
            </div>
        </div>
    </div>
    <div id="portraits-bw" class="container">
        <div class="row">
            <div keyboard = true data-interval="10000" id="portraits-bw-carousel" class="index-padding-10per carousel slide" data-ride="carousel">

              <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    {% for image in bw_portraits %}
                       {% if forloop.first %}
                        <div class="item active">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% else %}
                        <div class="item">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>

              <!-- Controls -->
                <a class="left carousel-control" href="#portraits-bw-carousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#portraits-bw-carousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                </a>
            </div>
        </div>
    </div>
    <div id="landscapes" class="container">
        <div class="row">
            <div keyboard = true data-interval="10000" id="landscape-carousel" class="index-padding-10per carousel slide" data-ride="carousel">

              <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    {% for image in landscape %}
                        {% if forloop.first %}
                        <div class="item active">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% else %}
                        <div class="item">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>

              <!-- Controls -->
                <a class="left carousel-control" href="#landscape-carousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#landscape-carousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                </a>
            </div>
        </div>
    </div>
    <div id="flowers" class="container">
        <div class="row">
            <div pause = 'hover' keyboard = true data-interval="10000" id="flowers-carousel" class="index-padding-10per carousel slide" data-ride="carousel">

              <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    {% for image in flowers %}
                       {% if forloop.first %}
                        <div class="item active">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% else %}
                        <div class="item">
                            <img src="{{ image.image.url }}" class="img-responsive">
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>

              <!-- Controls -->
                <a class="left carousel-control" href="#flowers-carousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#flowers-carousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                </a>
            </div>
        </div>
    </div>
    <a href="#top" class="to-top"><i class="fa fa-arrow-circle-up" aria-hidden="true"></i></a>
{% endblock %}

templates/store/store_index.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

templates/works/flowers_all.html
{% extends 'base.html' %}

{% block content %}
<div id="flowers" class="container">
    <div class="row">
        <div pause = 'hover' keyboard = true data-interval="10000" id="flowers-carousel" class=" carousel slide" data-ride="carousel">

          <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                {% for image in object_list %}
                   {% if forloop.first %}
                    <div class="item active">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% else %}
                    <div class="item">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% endif %}
                {% endfor %}
            </div>

          <!-- Controls -->
            <a class="left carousel-control" href="#flowers-carousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#flowers-carousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/works/landscapes_all.html
{% extends 'base.html' %}

{% block content %}
<div id="landscapes" class="container">
    <div class="row">
        <div pause = 'hover' keyboard = true data-interval="10000" id="flowers-carousel" class="index-padding-10per carousel slide" data-ride="carousel">

          <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                {% for image in object_list %}
                   {% if forloop.first %}
                    <div class="item active">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% else %}
                    <div class="item">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% endif %}
                {% endfor %}
            </div>

          <!-- Controls -->
            <a class="left carousel-control" href="#flowers-carousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#flowers-carousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/works/portraits_all.html
{% extends 'base.html' %}

{% block content %}
<div id="portraits" class="container">
    <div class="row">
        <div pause = 'hover' keyboard = true data-interval="10000" id="flowers-carousel" class="index-padding-10per carousel slide" data-ride="carousel">

          <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                {% for image in object_list %}
                   {% if forloop.first %}
                    <div class="item active">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% else %}
                    <div class="item">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% endif %}
                {% endfor %}
            </div>

          <!-- Controls -->
            <a class="left carousel-control" href="#flowers-carousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#flowers-carousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/works/portraits_bw_all.html
{% extends 'base.html' %}

{% block content %}
<div id="portraits_bw" class="container">
    <div class="row">
        <div pause = 'hover' keyboard = true data-interval="10000" id="flowers-carousel" class="index-padding-10per carousel slide" data-ride="carousel">

          <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                {% for image in object_list %}
                   {% if forloop.first %}
                    <div class="item active">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% else %}
                    <div class="item">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% endif %}
                {% endfor %}
            </div>

          <!-- Controls -->
            <a class="left carousel-control" href="#flowers-carousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#flowers-carousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/works/zoo_all.html
{% extends 'base.html' %}

{% block content %}
<div id="zoo" class="container">
    <div class="row">
        <div pause = 'hover' keyboard = true data-interval="10000" id="flowers-carousel" class="index-padding-10per carousel slide" data-ride="carousel">

          <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                {% for image in object_list %}
                   {% if forloop.first %}
                    <div class="item active">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% else %}
                    <div class="item">
                        <img src="{{ image.image.url }}" class="img-responsive">
                    </div>
                    {% endif %}
                {% endfor %}
            </div>

          <!-- Controls -->
            <a class="left carousel-control" href="#flowers-carousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#flowers-carousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            </a>
        </div>
    </div>
</div>
{% endblock %}